services:
  postgres:
    image: postgres:16-alpine
    container_name: promo-codes-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: promo_codes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
